# permissions for end users to edit pluginconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pluginconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nri-plugins-operator
    app.kubernetes.io/part-of: nri-plugins-operator
    app.kubernetes.io/managed-by: kustomize
  name: pluginconfig-editor-role
rules:
- apiGroups:
  - apps.nri.io
  resources:
  - pluginconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.nri.io
  resources:
  - pluginconfigs/status
  verbs:
  - get
