---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
      - serviceaccounts
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for apps.nri.io/v1alpha1, Kind: PluginConfig
  ##
  - apiGroups:
      - apps.nri.io
    resources:
      - pluginconfigs
      - pluginconfigs/status
      - pluginconfigs/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - topology.node.k8s.io
    resources:
      - noderesourcetopologies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:  # 2nd API group
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
  - verbs:
    - "*"
    apiGroups:
    - "rbac.authorization.k8s.io"
    resources:
    - "clusterrolebindings"
    - "clusterroles"
  - verbs:
    - "*"
    apiGroups:
    - "rbac.authorization.k8s.io"
    resources:
    - "rolebindings"
    - "roles"
  - verbs:
    - "*"
    apiGroups:
    - "apps"
    resources:
    - "daemonsets"
  - verbs:
    - "*"
    apiGroups:
    - ""
    resources:
    - "configmaps"
    - "serviceaccounts"
    - "namespaces"
